# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More


# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
disqus_shortname: finmuch
share_enabled: true
google_analytics:
favicon: /favicon/favicon.ico
twitter:
instagram:
pinterest:
github:
google_plus:
fb_admins:
fb_app_id:
